### ISSUE TITLE
UI - Blank Screen until Action is triggered.

### ISSUE THREAD

**Issue by Caboose885** [CrunchyData/crunchy-postgresql-manager#30]
UI in CPM generates dummy items in the right pane when CPM is empty. This can be confusing because CPM isn't in a ready state to accept user information. Right pane should be empty until the left pane action button is triggered.

Places Affected
-----------------------
Clusters
Containers
Schedule
Servers

**Comment by jmccormick2001** [comment]
commited fixes for this.
