### ISSUE TITLE
403 Access Denied for cpm.0.9.4-linux-amd64.tar.gz

### ISSUE THREAD

**Issue by brazenbraden** [CrunchyData/crunchy-postgresql-manager#89]
Been trying to download the latest CPM at https://s3.amazonaws.com/crunchydata/cpm/cpm.0.9.4-linux-amd64.tar.gz however it throws a 403. I  have tested the other endpoints in the API and they seem to work fine. cpm.0.9.3 is downloadable but no cigar with 0.9.4.

**Comment by jmccormick2001** [comment]
thanks, let me take a look into that.

Jeff

**Comment by jmccormick2001** [comment]
should be fixed now.  ps.  I should have a new version out this week as well.
